### ISSUE TITLE
Title Component

### ISSUE THREAD

**Issue by SafeDuck** [Rose-Hacks/rosehack2024#20]
![image](https://github.com/Rose-Hacks/rosehack2024/assets/49844738/7c824186-fcd8-41d3-bd96-12f545c92aa3)

Prop: text

path: src/components/static/prelive/Title.jsx

the triangle assets are in the public/svg folder

**Comment by fardinzam** [comment]
I went through all of these and I couldn't find the SVG arrow, has it not been added or am I just missing it somewhere?
<img width="404" alt="Screenshot 2023-10-28 at 9 01 00 PM" src="https://github.com/Rose-Hacks/rosehack2024/assets/55073341/f8c8e8d9-92dd-4f80-9ef1-d2d9cd5d5d8f">
