### ISSUE TITLE
1 Color blue backdrop (board)

### ISSUE THREAD

**Issue by SafeDuck** [Rose-Hacks/rosehack2024#41]
![image](https://github.com/Rose-Hacks/rosehack2024/assets/49844738/16e03d19-2601-44ed-8c0b-84d065ed58b1)

Make the backdrop of the board a single color. 
The board members from different colors, which are defined in src/data/static/Board.js

**Comment by fardinzam** [comment]
background is already a uniform black on the site currently, what do you mean by the second line?
