### ISSUE TITLE
Increase the count per row Board

### ISSUE THREAD

**Issue by SafeDuck** [Rose-Hacks/rosehack2024#90]
right now it's too much scrolling. Make it similar to how it looks on cutiehack:
![image](https://github.com/Rose-Hacks/rosehack2024/assets/49844738/ca03f95c-2699-4324-90cc-a18ef6b4f4e1)
![image](https://github.com/Rose-Hacks/rosehack2024/assets/49844738/0ab08633-d333-4f66-91cf-414a3a9f390a)

**Comment by fardinzam** [comment]
covered by "Add Judges" pr
